import assert from 'node:assert/strict';
import { createSystem, advance, environment, destruction, accelerations } from '../src/physics.mjs';
const world = createSystem(12);
world.days = 3650;
advance(world, .001);
assert.equal(world.death.type, 'victory');
const days = world.days;
advance(world, 2);
assert.equal(world.days, days);
const doomed = createSystem(12);
doomed.days = 3650;
doomed.bodies[3].p = [...doomed.bodies[0].p];
advance(doomed, .01);
assert.equal(doomed.death.type, 'collision');
const edited = createSystem(12);
const star = edited.bodies[0];
star.deleted = true; star.mass = 0; star.radius = 0; star.luminosity = 0;
star.p = [...edited.bodies[3].p];
edited.env = environment(edited.bodies);
assert.equal(destruction(edited), null);
assert.ok(Number.isFinite(edited.env.flux));
assert.ok(accelerations(edited.bodies).flat().every(Number.isFinite));
advance(edited, 1);
assert.ok(edited.days > 0);
console.log('PASS: victory, terminal freeze, destruction priority, deleted-star physics');
